### ISSUE TITLE
docker 部署+运行报错

### ISSUE THREAD

**Issue by Spider-DT** [HarrisonWang/url-shortener#1]
Hi,感谢贡献！

![20241006-1037-Fig](https://tuchuang-wangpeng.oss-cn-hangzhou.aliyuncs.com/tuchuang-wangpeng/20241006-1037-Fig.png)

docker compose up -d 执行后，提示参数缺失

![20241006-1037-Fig-1](https://tuchuang-wangpeng.oss-cn-hangzhou.aliyuncs.com/tuchuang-wangpeng/20241006-1037-Fig-1.png)

登入站点后，尝试生成短链，提示错误如上

---

### 请大佬指导下~

**Comment by Spider-DT** [comment]
应该是环境变量追加写入的部分有Bug，在 compose.yml 里将两个参数直接写入后，就可以了~
笨方法，哈哈

**Comment by harrisonwang** [comment]
将 `.env.example` 重命名为 `.env` ，配置以下环境变量后执行 `docker compose up -d` 命令即可。
```bash
NEXT_PUBLIC_SUPABASE_URL=xxx
NEXT_PUBLIC_SUPABASE_KEY=xxx
```


> Hi,感谢贡献！
> 
> ![20241006-1037-Fig](https://camo.githubusercontent.com/769b8b78e66f6fd81f983a22584a6e2970e510b72d3ad6a7f32903e90110cb89/68747470733a2f2f7475636875616e672d77616e6770656e672e6f73732d636e2d68616e677a686f752e616c6979756e63732e636f6d2f7475636875616e672d77616e6770656e672f32303234313030362d313033372d4669672e706e67)
> 
> docker compose up -d 执行后，提示参数缺失
> 
> ![20241006-1037-Fig-1](https://camo.githubusercontent.com/2bd02e71dad9f5b0b2b65d8cc39f388aa62e34eb809d6f2192a0c694cd512de2/68747470733a2f2f7475636875616e672d77616e6770656e672e6f73732d636e2d68616e677a686f752e616c6979756e63732e636f6d2f7475636875616e672d77616e6770656e672f32303234313030362d313033372d4669672d312e706e67)
> 
> 登入站点后，尝试生成短链，提示错误如上
> 
> ### 请大佬指导下~
